language: python

install: true

script: echo "This is a deployment-only CI script. There are no tests run."

deploy:
  provider: pypi
  user: arjungmenon
  password:
    secure: ZWHunVRATwgC76rr5N2GelrKxHU1Y+yagkRCLetVZx9yOEtrXVFlQNLYcdX7EY8BjapJia3azdBijsi7cnHecfgywpfXLvpbt+5giKSmtgpGpVt+MInsxotry4/tmH9BTDNI89DHzoeuagJVvguI6xcm80PumhMvb9gkTE+9obI=
  on:
    tags: true
